# Generated by Django 4.2.10 on 2024-03-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_sitesetup_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='favicon',
        ),
    ]
